/* Generated by Frama-C */
#include "stddef.h"
#include "stdio.h"
int control_temperature(int temperature, int fan_speed, int mode,
                        int humidity_level)
{
  if (mode == 1) temperature -= fan_speed;
  else 
    if (mode == 2) temperature += fan_speed;
  if (humidity_level >= 20) 
    if (humidity_level <= 80) 
      if (temperature < 200) {
        int humidity_effect = (humidity_level * 5) / 10;
        temperature += humidity_effect;
      }
  return temperature;
}

int main() {
  int temperature = 250;       // Initial room temperature: 25.0°C
  int fan_speed = 5;           // Fan speed in tenths of degree
  int mode = 1;                // Mode: 1 for cooling, 2 for heating
  int humidity_level = 60;     // Humidity level (affects comfort but not directly safety)

  int final_temperature = control_temperature(temperature, fan_speed, mode, humidity_level);
  printf("Final temperature: %d.%d°C\n", final_temperature / 10, final_temperature % 10);
  return 0;
}



