/* Generated by Frama-C */
#include "stddef.h"
#include "stdio.h"
int control_fan_speed(int temperature, int fan_speed, int system_mode,
                      int operating_hours)
{
  if (! (system_mode == 0)) 
    if (system_mode == 1) 
      if (fan_speed < 90) 
        if (temperature > 30) fan_speed += 5;
        else 
          if (temperature < 20) fan_speed -= 5;
  if (operating_hours > 100) 
    if (fan_speed < 95) fan_speed ++;
  return fan_speed;
}


