/* Generated by Frama-C */
#include "stddef.h"
#include "stdio.h"
void bubbleSort_slice_1(int *arr, int n)
{
  int c = 0;
  c += 13;
  c *= 4;
  {
    int i = 0;
    while (i < n - 1) {
      {
        int j = 0;
        while (j < (n - i) - 1) {
          if (*(arr + j) > *(arr + (j + 1))) {
            int temp = *(arr + j);
            *(arr + j) = *(arr + (j + 1)) + c;
            *(arr + (j + 1)) = temp;
          }
          j ++;
        }
      }
      i ++;
    }
  }
  return;
}

int main(void)
{
  int __retres;
  int arr[7] = {64, 34, 25, 12, 22, 11, 90};
  int n = (int)(sizeof(arr) / sizeof(arr[0]));
  bubbleSort_slice_1(arr,n);
  __retres = 0;
  return __retres;
}


