// [kernel] Parsing constantFolding.c (with preprocessing)
// [scf] beginning constant propagation
// [eva] Analyzing a complete application starting at main
// [eva:initial-state] Values of globals at initialization
  
// [eva] using specification for function printf_va_1
// [eva] using specification for function printf_va_2
// [eva] using specification for function printf_va_3
// [eva] using specification for function printf_va_5
// [eva:summary] ====== ANALYSIS SUMMARY ======
//   ----------------------------------------------------------------------------
//   5 functions analyzed (out of 5): 100% coverage.
//   In these functions, 22 statements reached (out of 23): 95% coverage.
//   ----------------------------------------------------------------------------
//   No errors or warnings raised during the analysis.
//   ----------------------------------------------------------------------------
//   0 alarms generated by the analysis.
//   ----------------------------------------------------------------------------
//   Evaluation of the logical properties reached by the analysis:
//     Assertions        0 valid     0 unknown     0 invalid      0 total
//     Preconditions     4 valid     0 unknown     0 invalid      4 total
//   100% of the logical properties reached have been proven.
//   ----------------------------------------------------------------------------
/* Generated by Frama-C */
#include "errno.h"
#include "stdarg.h"
#include "stddef.h"
#include "stdio.h"
/*@ requires valid_read_string(format);
    assigns \result, __fc_stdout->__fc_FILE_data;
    assigns \result
      \from (indirect: __fc_stdout->__fc_FILE_id),
            (indirect: __fc_stdout->__fc_FILE_data),
            (indirect: *(format + (0 ..))), (indirect: param0);
    assigns __fc_stdout->__fc_FILE_data
      \from (indirect: __fc_stdout->__fc_FILE_id),
            __fc_stdout->__fc_FILE_data, (indirect: *(format + (0 ..))),
            param0;
 */
int printf_va_1(char const * restrict format, int param0);

void constant_folding_example(void)
{
  int a = 8;
  printf("Value of a: %d\n",8); /* printf_va_1 */
  return;
}

/*@ requires valid_read_string(format);
    assigns \result, __fc_stdout->__fc_FILE_data;
    assigns \result
      \from (indirect: __fc_stdout->__fc_FILE_id),
            (indirect: __fc_stdout->__fc_FILE_data),
            (indirect: *(format + (0 ..))), (indirect: param0);
    assigns __fc_stdout->__fc_FILE_data
      \from (indirect: __fc_stdout->__fc_FILE_id),
            __fc_stdout->__fc_FILE_data, (indirect: *(format + (0 ..))),
            param0;
 */
int printf_va_2(char const * restrict format, int param0);

void constant_propagation_example(void)
{
  int x = 10;
  int y = 20;
  printf("Value of y: %d\n",20); /* printf_va_2 */
  return;
}

/*@ requires valid_read_string(format);
    assigns \result, __fc_stdout->__fc_FILE_data;
    assigns \result
      \from (indirect: __fc_stdout->__fc_FILE_id),
            (indirect: __fc_stdout->__fc_FILE_data),
            (indirect: *(format + (0 ..)));
    assigns __fc_stdout->__fc_FILE_data
      \from (indirect: __fc_stdout->__fc_FILE_id),
            __fc_stdout->__fc_FILE_data, (indirect: *(format + (0 ..)));
 */
int printf_va_3(char const * restrict format);

/*@ requires valid_read_string(format);
    assigns \result, __fc_stdout->__fc_FILE_data;
    assigns \result
      \from (indirect: __fc_stdout->__fc_FILE_id),
            (indirect: __fc_stdout->__fc_FILE_data),
            (indirect: *(format + (0 ..)));
    assigns __fc_stdout->__fc_FILE_data
      \from (indirect: __fc_stdout->__fc_FILE_id),
            __fc_stdout->__fc_FILE_data, (indirect: *(format + (0 ..)));
 */
int printf_va_4(char const * restrict format);

void redundant_branch_example(void)
{
  int x = 5;
  if (1) printf("x is positive\n"); /* printf_va_3 */
  else printf("x is non-positive\n"); /* printf_va_4 */
  return;
}

/*@ requires valid_read_string(format);
    assigns \result, __fc_stdout->__fc_FILE_data;
    assigns \result
      \from (indirect: __fc_stdout->__fc_FILE_id),
            (indirect: __fc_stdout->__fc_FILE_data),
            (indirect: *(format + (0 ..))), (indirect: param0);
    assigns __fc_stdout->__fc_FILE_data
      \from (indirect: __fc_stdout->__fc_FILE_id),
            __fc_stdout->__fc_FILE_data, (indirect: *(format + (0 ..))),
            param0;
 */
int printf_va_5(char const * restrict format, int param0);

void compile_time_constant_example(void)
{
  int const a = 7;
  int const b = 3;
  int result = 21;
  printf("Result: %d\n",21); /* printf_va_5 */
  return;
}

int main(void)
{
  int __retres;
  constant_folding_example();
  constant_propagation_example();
  redundant_branch_example();
  compile_time_constant_example();
  __retres = 0;
  return __retres;
}


// [scf] constant propagation done
