/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 2 "pid_controller_preprocessed.c"
typedef unsigned long size_t;
#line 3 "pid_controller_preprocessed.c"
typedef long ssize_t;
#line 4 "pid_controller_preprocessed.c"
typedef long off_t;
#line 5
struct _IO_FILE;
#line 5 "pid_controller_preprocessed.c"
typedef struct _IO_FILE FILE;
#line 6 "pid_controller_preprocessed.c"
typedef __builtin_va_list va_list;
#line 7 "pid_controller_preprocessed.c"
typedef __builtin_va_list __isoc_va_list;
#line 8 "pid_controller_preprocessed.c"
union _G_fpos64_t {
   char __opaque[16] ;
   long long __lldata ;
   double __align ;
};
#line 8 "pid_controller_preprocessed.c"
typedef union _G_fpos64_t fpos_t;
#line 101 "pid_controller_preprocessed.c"
typedef int wchar_t;
#line 129 "pid_controller_preprocessed.c"
struct __anonstruct_div_t_1 {
   int quot ;
   int rem ;
};
#line 129 "pid_controller_preprocessed.c"
typedef struct __anonstruct_div_t_1 div_t;
#line 130 "pid_controller_preprocessed.c"
struct __anonstruct_ldiv_t_2 {
   long quot ;
   long rem ;
};
#line 130 "pid_controller_preprocessed.c"
typedef struct __anonstruct_ldiv_t_2 ldiv_t;
#line 131 "pid_controller_preprocessed.c"
struct __anonstruct_lldiv_t_3 {
   long long quot ;
   long long rem ;
};
#line 131 "pid_controller_preprocessed.c"
typedef struct __anonstruct_lldiv_t_3 lldiv_t;
#line 181 "pid_controller_preprocessed.c"
struct __anonstruct_PID_4 {
   float Kp ;
   float Ki ;
   float Kd ;
   float Kaw ;
   float T_C ;
   float T ;
   float max ;
   float min ;
   float max_rate ;
   float integral ;
   float err_prev ;
   float deriv_prev ;
   float command_prev ;
   float command_sat_prev ;
};
#line 181 "pid_controller_preprocessed.c"
typedef struct __anonstruct_PID_4 PID;
#line 187 "pid_controller_preprocessed.c"
struct __anonstruct_Object_5 {
   float m ;
   float k ;
   float F_max ;
   float F_min ;
   float T ;
   float v ;
   float z ;
};
#line 187 "pid_controller_preprocessed.c"
typedef struct __anonstruct_Object_5 Object;
/* compiler builtin: 
   void __builtin_va_copy(__builtin_va_list  , __builtin_va_list  ) ;  */
/* compiler builtin: 
   double __builtin_huge_val(void) ;  */
/* compiler builtin: 
   int __builtin_clzl(unsigned long  ) ;  */
/* compiler builtin: 
   float __builtin_frexpf(float  , int * ) ;  */
/* compiler builtin: 
   long double __builtin_fmodl(long double  ) ;  */
/* compiler builtin: 
   double __builtin_atan(double  ) ;  */
/* compiler builtin: 
   int __builtin___fprintf_chk(void * , int  , char const   *  , ...) ;  */
/* compiler builtin: 
   float __builtin_ceilf(float  ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_and_and_fetch(...) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_fetch_and_or(...) ;  */
/* compiler builtin: 
   void __builtin_return(void const   * ) ;  */
/* compiler builtin: 
   int __builtin_popcountll(unsigned long long  ) ;  */
/* compiler builtin: 
   long double __builtin_asinl(long double  ) ;  */
/* compiler builtin: 
   float __builtin_atanf(float  ) ;  */
/* compiler builtin: 
   int __builtin_ffsll(unsigned long long  ) ;  */
/* compiler builtin: 
   float __attribute__((____vector_size____(16)))  __builtin_ia32_addps(float __attribute__((____vector_size____(16)))   ,
                                                                        float __attribute__((____vector_size____(16)))   ) ;  */
/* compiler builtin: 
   unsigned long __builtin_strcspn(char const   * , char const   * ) ;  */
/* compiler builtin: 
   float __builtin_asinf(float  ) ;  */
/* compiler builtin: 
   float __attribute__((____vector_size____(16)))  __builtin_ia32_maxps(float __attribute__((____vector_size____(16)))   ,
                                                                        float __attribute__((____vector_size____(16)))   ) ;  */
/* compiler builtin: 
   float __attribute__((____vector_size____(16)))  __builtin_ia32_unpckhps(float __attribute__((____vector_size____(16)))   ,
                                                                           float __attribute__((____vector_size____(16)))   ) ;  */
/* compiler builtin: 
   double __builtin_acos(double  ) ;  */
/* compiler builtin: 
   int __builtin_va_arg_pack(void) ;  */
/* compiler builtin: 
   char *__builtin___strncpy_chk(char * , char const   * , unsigned long  , unsigned long  ) ;  */
/* compiler builtin: 
   int __builtin___sprintf_chk(char * , int  , unsigned long  , char const   *  , ...) ;  */
/* compiler builtin: 
   double __builtin_powi(double  , int  ) ;  */
/* compiler builtin: 
   char *__builtin_strchr(char * , int  ) ;  */
/* compiler builtin: 
   char *__builtin___strncat_chk(char * , char const   * , unsigned long  , unsigned long  ) ;  */
/* compiler builtin: 
   long double __builtin_huge_vall(void) ;  */
/* compiler builtin: 
   int __builtin_ffsl(unsigned long  ) ;  */
/* compiler builtin: 
   int __builtin___vprintf_chk(int  , char const   * , __builtin_va_list  ) ;  */
/* compiler builtin: 
   float __attribute__((____vector_size____(16)))  __builtin_ia32_unpcklps(float __attribute__((____vector_size____(16)))   ,
                                                                           float __attribute__((____vector_size____(16)))   ) ;  */
/* compiler builtin: 
   char *__builtin_strncat(char * , char const   * , unsigned long  ) ;  */
/* compiler builtin: 
   int __builtin_ctzll(unsigned long long  ) ;  */
/* compiler builtin: 
   double __builtin_cosh(double  ) ;  */
/* compiler builtin: 
   void __builtin_stdarg_start(__builtin_va_list  ) ;  */
/* compiler builtin: 
   float __builtin_tanhf(float  ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_fetch_and_xor(...) ;  */
/* compiler builtin: 
   void *__builtin_mempcpy(void * , void const   * , unsigned long  ) ;  */
/* compiler builtin: 
   long double __builtin_frexpl(long double  , int * ) ;  */
/* compiler builtin: 
   float __builtin_tanf(float  ) ;  */
/* compiler builtin: 
   long double __builtin_logl(long double  ) ;  */
/* compiler builtin: 
   long double __builtin_sqrtl(long double  ) ;  */
/* compiler builtin: 
   int __builtin_parity(unsigned int  ) ;  */
/* compiler builtin: 
   void __builtin_va_arg(__builtin_va_list  , unsigned long  , void * ) ;  */
/* compiler builtin: 
   long __builtin_expect(long  , long  ) ;  */
/* compiler builtin: 
   long double __builtin_coshl(long double  ) ;  */
/* compiler builtin: 
   long double __builtin_cosl(long double  ) ;  */
/* compiler builtin: 
   float __builtin_cosf(float  ) ;  */
/* compiler builtin: 
   int __builtin___printf_chk(int  , char const   *  , ...) ;  */
/* compiler builtin: 
   void __sync_synchronize(...) ;  */
/* compiler builtin: 
   long double __builtin_acosl(long double  ) ;  */
/* compiler builtin: 
   int __builtin___vfprintf_chk(void * , int  , char const   * , __builtin_va_list  ) ;  */
/* compiler builtin: 
   void *__builtin___mempcpy_chk(void * , void const   * , unsigned long  , unsigned long  ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_or_and_fetch(...) ;  */
/* compiler builtin: 
   void __builtin_prefetch(void const   *  , ...) ;  */
/* compiler builtin: 
   long double __builtin_nansl(char const   * ) ;  */
/* compiler builtin: 
   double __builtin_fmod(double  ) ;  */
/* compiler builtin: 
   int __builtin_clz(unsigned int  ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_val_compare_and_swap(...) ;  */
/* compiler builtin: 
   double __builtin_log10(double  ) ;  */
/* compiler builtin: 
   char *__builtin___strcat_chk(char * , char const   * , unsigned long  ) ;  */
/* compiler builtin: 
   double __builtin_tanh(double  ) ;  */
/* compiler builtin: 
   float __builtin_modff(float  , float * ) ;  */
/* compiler builtin: 
   double __builtin_sin(double  ) ;  */
/* compiler builtin: 
   double __builtin_frexp(double  , int * ) ;  */
/* compiler builtin: 
   float __builtin_acosf(float  ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_add_and_fetch(...) ;  */
/* compiler builtin: 
   long double __builtin_sinhl(long double  ) ;  */
/* compiler builtin: 
   char *__builtin___stpcpy_chk(char * , char const   * , unsigned long  ) ;  */
/* compiler builtin: 
   long double __builtin_ldexpl(long double  , int  ) ;  */
/* compiler builtin: 
   double __builtin_fabs(double  ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_fetch_and_nand(...) ;  */
/* compiler builtin: 
   void *__builtin_apply(void (*)() , void * , unsigned long  ) ;  */
/* compiler builtin: 
   float __builtin_sinf(float  ) ;  */
/* compiler builtin: 
   double __builtin_ceil(double  ) ;  */
/* compiler builtin: 
   long double __builtin_powil(long double  , int  ) ;  */
/* compiler builtin: 
   void __builtin_va_start(__builtin_va_list  ) ;  */
/* compiler builtin: 
   long double __builtin_expl(long double  ) ;  */
/* compiler builtin: 
   int __builtin_constant_p(int  ) ;  */
/* compiler builtin: 
   double __builtin_log(double  ) ;  */
/* compiler builtin: 
   float __builtin_expf(float  ) ;  */
/* compiler builtin: 
   int __builtin_types_compatible_p(unsigned long  , unsigned long  ) ;  */
/* compiler builtin: 
   int __builtin_ctz(unsigned int  ) ;  */
/* compiler builtin: 
   long double __builtin_atan2l(long double  , long double  ) ;  */
/* compiler builtin: 
   void *__builtin_apply_args(void) ;  */
/* compiler builtin: 
   char *__builtin_strpbrk(char const   * , char const   * ) ;  */
/* compiler builtin: 
   char *__builtin_strcpy(char * , char const   * ) ;  */
/* compiler builtin: 
   double __builtin_sqrt(double  ) ;  */
/* compiler builtin: 
   __builtin_va_list __builtin_next_arg(void) ;  */
/* compiler builtin: 
   float __builtin_logf(float  ) ;  */
/* compiler builtin: 
   float __builtin_log10f(float  ) ;  */
/* compiler builtin: 
   long double __builtin_fabsl(long double  ) ;  */
/* compiler builtin: 
   unsigned long __builtin_strlen(char const   * ) ;  */
/* compiler builtin: 
   long double __builtin_floorl(long double  ) ;  */
/* compiler builtin: 
   int __builtin_ffs(unsigned int  ) ;  */
/* compiler builtin: 
   double __builtin_inf(void) ;  */
/* compiler builtin: 
   float __builtin_floorf(float  ) ;  */
/* compiler builtin: 
   void *__builtin_memcpy(void * , void const   * , unsigned long  ) ;  */
/* compiler builtin: 
   void *__builtin___memcpy_chk(void * , void const   * , unsigned long  , unsigned long  ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_sub_and_fetch(...) ;  */
/* compiler builtin: 
   int __builtin_parityl(unsigned long  ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_nand_and_fetch(...) ;  */
/* compiler builtin: 
   float __attribute__((____vector_size____(16)))  __builtin_ia32_subps(float __attribute__((____vector_size____(16)))   ,
                                                                        float __attribute__((____vector_size____(16)))   ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_lock_test_and_set(...) ;  */
/* compiler builtin: 
   unsigned long __builtin_strspn(char const   * , char const   * ) ;  */
/* compiler builtin: 
   void __builtin_varargs_start(__builtin_va_list  ) ;  */
/* compiler builtin: 
   int __builtin_parityll(unsigned long long  ) ;  */
/* compiler builtin: 
   void __builtin_va_end(__builtin_va_list  ) ;  */
/* compiler builtin: 
   void __builtin_bzero(void * , unsigned long  ) ;  */
/* compiler builtin: 
   int __builtin_strncmp(char const   * , char const   * , unsigned long  ) ;  */
/* compiler builtin: 
   double __builtin_nan(char const   * ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_xor_and_fetch(...) ;  */
/* compiler builtin: 
   int __builtin___vsprintf_chk(char * , int  , unsigned long  , char const   * ,
                                __builtin_va_list  ) ;  */
/* compiler builtin: 
   int __builtin___snprintf_chk(char * , unsigned long  , int  , unsigned long  ,
                                char const   *  , ...) ;  */
/* compiler builtin: 
   float __builtin_sqrtf(float  ) ;  */
/* compiler builtin: 
   double __builtin_nans(char const   * ) ;  */
/* compiler builtin: 
   long double __builtin_atanl(long double  ) ;  */
/* compiler builtin: 
   double __builtin_exp(double  ) ;  */
/* compiler builtin: 
   int __builtin_clzll(unsigned long long  ) ;  */
/* compiler builtin: 
   float __builtin_huge_valf(void) ;  */
/* compiler builtin: 
   float __builtin_coshf(float  ) ;  */
/* compiler builtin: 
   float __builtin_nansf(char const   * ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_fetch_and_add(...) ;  */
/* compiler builtin: 
   int __builtin___vsnprintf_chk(char * , unsigned long  , int  , unsigned long  ,
                                 char const   * , __builtin_va_list  ) ;  */
/* compiler builtin: 
   float __builtin_nanf(char const   * ) ;  */
/* compiler builtin: 
   int __builtin_strcmp(char const   * , char const   * ) ;  */
/* compiler builtin: 
   _Bool __sync_bool_compare_and_swap(...) ;  */
/* compiler builtin: 
   float __builtin_ldexpf(float  , int  ) ;  */
/* compiler builtin: 
   double __builtin_atan2(double  , double  ) ;  */
/* compiler builtin: 
   int __builtin_popcountl(unsigned long  ) ;  */
/* compiler builtin: 
   float __builtin_powif(float  , int  ) ;  */
/* compiler builtin: 
   long double __builtin_ceill(long double  ) ;  */
/* compiler builtin: 
   char *__builtin___strcpy_chk(char * , char const   * , unsigned long  ) ;  */
/* compiler builtin: 
   long double __builtin_log10l(long double  ) ;  */
/* compiler builtin: 
   void *__builtin___memmove_chk(void * , void const   * , unsigned long  , unsigned long  ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_fetch_and_and(...) ;  */
/* compiler builtin: 
   void *__builtin_return_address(unsigned int  ) ;  */
/* compiler builtin: 
   float __builtin_fabsf(float  ) ;  */
/* compiler builtin: 
   double __builtin_floor(double  ) ;  */
/* compiler builtin: 
   double __builtin_cos(double  ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_fetch_and_sub(...) ;  */
/* compiler builtin: 
   unsigned long __builtin_object_size(void * , int  ) ;  */
/* compiler builtin: 
   void *__builtin_memset(void * , int  , int  ) ;  */
/* compiler builtin: 
   void *__builtin_alloca(unsigned long  ) ;  */
/* compiler builtin: 
   long double __builtin_nanl(char const   * ) ;  */
/* compiler builtin: 
   float __builtin_atan2f(float  , float  ) ;  */
/* compiler builtin: 
   int __builtin_popcount(unsigned int  ) ;  */
/* compiler builtin: 
   int __builtin_va_arg_pack_len(void) ;  */
/* compiler builtin: 
   long double __builtin_tanl(long double  ) ;  */
/* compiler builtin: 
   double __builtin_sinh(double  ) ;  */
/* compiler builtin: 
   void __builtin_bcopy(void const   * , void * , unsigned long  ) ;  */
/* compiler builtin: 
   void __sync_lock_release(...) ;  */
/* compiler builtin: 
   long double __builtin_modfl(long double  , long double * ) ;  */
/* compiler builtin: 
   char *__builtin_stpcpy(char * , char const   * ) ;  */
/* compiler builtin: 
   long double __builtin_sinl(long double  ) ;  */
/* compiler builtin: 
   double __builtin_asin(double  ) ;  */
/* compiler builtin: 
   float __builtin_sinhf(float  ) ;  */
/* compiler builtin: 
   int __builtin_ctzl(unsigned long  ) ;  */
/* compiler builtin: 
   long double __builtin_tanhl(long double  ) ;  */
/* compiler builtin: 
   int __builtin_bswap32(int  ) ;  */
/* compiler builtin: 
   double __builtin_ldexp(double  , int  ) ;  */
/* compiler builtin: 
   long double __builtin_infl(void) ;  */
/* compiler builtin: 
   long __builtin_bswap64(long  ) ;  */
/* compiler builtin: 
   float __builtin_fmodf(float  ) ;  */
/* compiler builtin: 
   float __attribute__((____vector_size____(16)))  __builtin_ia32_mulps(float __attribute__((____vector_size____(16)))   ,
                                                                        float __attribute__((____vector_size____(16)))   ) ;  */
/* compiler builtin: 
   double __builtin_tan(double  ) ;  */
/* compiler builtin: 
   char *__builtin_strncpy(char * , char const   * , unsigned long  ) ;  */
/* compiler builtin: 
   float __builtin_inff(void) ;  */
/* compiler builtin: 
   void *__builtin___memset_chk(void * , int  , unsigned long  , unsigned long  ) ;  */
/* compiler builtin: 
   void *__builtin_frame_address(unsigned int  ) ;  */
#line 13
extern FILE * const  stdin ;
#line 14
extern FILE * const  stdout ;
#line 15
extern FILE * const  stderr ;
#line 16
extern FILE *fopen(char const   * __restrict   , char const   * __restrict   ) ;
#line 17
extern FILE *freopen(char const   * __restrict   , char const   * __restrict   , FILE * __restrict   ) ;
#line 18
extern int fclose(FILE * ) ;
#line 19
extern int remove(char const   * ) ;
#line 20
extern int rename(char const   * , char const   * ) ;
#line 21
extern int feof(FILE * ) ;
#line 22
extern int ferror(FILE * ) ;
#line 23
extern int fflush(FILE * ) ;
#line 24
extern void clearerr(FILE * ) ;
#line 25
extern int fseek(FILE * , long  , int  ) ;
#line 26
extern long ftell(FILE * ) ;
#line 27
extern void rewind(FILE * ) ;
#line 28
extern int fgetpos(FILE * __restrict   , fpos_t * __restrict   ) ;
#line 29
extern int fsetpos(FILE * , fpos_t const   * ) ;
#line 30
extern size_t fread(void * __restrict   , size_t  , size_t  , FILE * __restrict   ) ;
#line 31
extern size_t fwrite(void const   * __restrict   , size_t  , size_t  , FILE * __restrict   ) ;
#line 32
extern int fgetc(FILE * ) ;
#line 33
extern int getc(FILE * ) ;
#line 34
extern int getchar(void) ;
#line 35
extern int ungetc(int  , FILE * ) ;
#line 36
extern int fputc(int  , FILE * ) ;
#line 37
extern int putc(int  , FILE * ) ;
#line 38
extern int putchar(int  ) ;
#line 39
extern char *fgets(char * __restrict   , int  , FILE * __restrict   ) ;
#line 40
extern int fputs(char const   * __restrict   , FILE * __restrict   ) ;
#line 41
extern int puts(char const   * ) ;
#line 42
extern int printf(char const   * __restrict    , ...) ;
#line 43
extern int fprintf(FILE * __restrict   , char const   * __restrict    , ...) ;
#line 44
extern int sprintf(char * __restrict   , char const   * __restrict    , ...) ;
#line 45
extern int snprintf(char * __restrict   , size_t  , char const   * __restrict    , ...) ;
#line 46
extern int vprintf(char const   * __restrict   , __isoc_va_list  ) ;
#line 47
extern int vfprintf(FILE * __restrict   , char const   * __restrict   , __isoc_va_list  ) ;
#line 48
extern int vsprintf(char * __restrict   , char const   * __restrict   , __isoc_va_list  ) ;
#line 49
extern int vsnprintf(char * __restrict   , size_t  , char const   * __restrict   ,
                     __isoc_va_list  ) ;
#line 50
extern int scanf(char const   * __restrict    , ...) ;
#line 51
extern int fscanf(FILE * __restrict   , char const   * __restrict    , ...) ;
#line 52
extern int sscanf(char const   * __restrict   , char const   * __restrict    , ...) ;
#line 53
extern int vscanf(char const   * __restrict   , __isoc_va_list  ) ;
#line 54
extern int vfscanf(FILE * __restrict   , char const   * __restrict   , __isoc_va_list  ) ;
#line 55
extern int vsscanf(char const   * __restrict   , char const   * __restrict   , __isoc_va_list  ) ;
#line 56
extern void perror(char const   * ) ;
#line 57
extern int setvbuf(FILE * __restrict   , char * __restrict   , int  , size_t  ) ;
#line 58
extern void setbuf(FILE * __restrict   , char * __restrict   ) ;
#line 59
extern char *tmpnam(char * ) ;
#line 60
extern FILE *tmpfile(void) ;
#line 61
extern FILE *fmemopen(void * __restrict   , size_t  , char const   * __restrict   ) ;
#line 62
extern FILE *open_memstream(char ** , size_t * ) ;
#line 63
extern FILE *fdopen(int  , char const   * ) ;
#line 64
extern FILE *popen(char const   * , char const   * ) ;
#line 65
extern int pclose(FILE * ) ;
#line 66
extern int fileno(FILE * ) ;
#line 67
extern int fseeko(FILE * , off_t  , int  ) ;
#line 68
extern off_t ftello(FILE * ) ;
#line 69
extern int dprintf(int  , char const   * __restrict    , ...) ;
#line 70
extern int vdprintf(int  , char const   * __restrict   , __isoc_va_list  ) ;
#line 71
extern void flockfile(FILE * ) ;
#line 72
extern int ftrylockfile(FILE * ) ;
#line 73
extern void funlockfile(FILE * ) ;
#line 74
extern int getc_unlocked(FILE * ) ;
#line 75
extern int getchar_unlocked(void) ;
#line 76
extern int putc_unlocked(int  , FILE * ) ;
#line 77
extern int putchar_unlocked(int  ) ;
#line 78
extern ssize_t getdelim(char ** __restrict   , size_t * __restrict   , int  , FILE * __restrict   ) ;
#line 79
extern ssize_t getline(char ** __restrict   , size_t * __restrict   , FILE * __restrict   ) ;
#line 80
extern int renameat(int  , char const   * , int  , char const   * ) ;
#line 81
extern char *ctermid(char * ) ;
#line 82
extern char *tempnam(char const   * , char const   * ) ;
#line 83
extern char *cuserid(char * ) ;
#line 84
extern void setlinebuf(FILE * ) ;
#line 85
extern void setbuffer(FILE * , char * , size_t  ) ;
#line 86
extern int fgetc_unlocked(FILE * ) ;
#line 87
extern int fputc_unlocked(int  , FILE * ) ;
#line 88
extern int fflush_unlocked(FILE * ) ;
#line 89
extern size_t fread_unlocked(void * , size_t  , size_t  , FILE * ) ;
#line 90
extern size_t fwrite_unlocked(void const   * , size_t  , size_t  , FILE * ) ;
#line 91
extern void clearerr_unlocked(FILE * ) ;
#line 92
extern int feof_unlocked(FILE * ) ;
#line 93
extern int ferror_unlocked(FILE * ) ;
#line 94
extern int fileno_unlocked(FILE * ) ;
#line 95
extern int getw(FILE * ) ;
#line 96
extern int putw(int  , FILE * ) ;
#line 97
extern char *fgetln(FILE * , size_t * ) ;
#line 98
extern int asprintf(char ** , char const   *  , ...) ;
#line 99
extern int vasprintf(char ** , char const   * , __isoc_va_list  ) ;
#line 102
extern int atoi(char const   * ) ;
#line 103
extern long atol(char const   * ) ;
#line 104
extern long long atoll(char const   * ) ;
#line 105
extern double atof(char const   * ) ;
#line 106
extern float strtof(char const   * __restrict   , char ** __restrict   ) ;
#line 107
extern double strtod(char const   * __restrict   , char ** __restrict   ) ;
#line 108
extern long double strtold(char const   * __restrict   , char ** __restrict   ) ;
#line 109
extern long strtol(char const   * __restrict   , char ** __restrict   , int  ) ;
#line 110
extern unsigned long strtoul(char const   * __restrict   , char ** __restrict   ,
                             int  ) ;
#line 111
extern long long strtoll(char const   * __restrict   , char ** __restrict   , int  ) ;
#line 112
extern unsigned long long strtoull(char const   * __restrict   , char ** __restrict   ,
                                   int  ) ;
#line 113
extern int rand(void) ;
#line 114
extern void srand(unsigned int  ) ;
#line 115
extern void *malloc(size_t  ) ;
#line 116
extern void *calloc(size_t  , size_t  ) ;
#line 117
extern void *realloc(void * , size_t  ) ;
#line 118
extern void free(void * ) ;
#line 119
extern void *aligned_alloc(size_t  , size_t  ) ;
#line 120
extern int atexit(void (*)(void) ) ;
#line 121
extern int at_quick_exit(void (*)(void) ) ;
#line 122
extern char *getenv(char const   * ) ;
#line 123
extern int system(char const   * ) ;
#line 124
extern void *bsearch(void const   * , void const   * , size_t  , size_t  , int (*)(void const   * ,
                                                                                   void const   * ) ) ;
#line 125
extern void qsort(void * , size_t  , size_t  , int (*)(void const   * , void const   * ) ) ;
#line 126
extern int abs(int  ) ;
#line 127
extern long labs(long  ) ;
#line 128
extern long long llabs(long long  ) ;
#line 132
extern div_t div(int  , int  ) ;
#line 133
extern ldiv_t ldiv(long  , long  ) ;
#line 134
extern lldiv_t lldiv(long long  , long long  ) ;
#line 135
extern int mblen(char const   * , size_t  ) ;
#line 136
extern int mbtowc(wchar_t * __restrict   , char const   * __restrict   , size_t  ) ;
#line 137
extern int wctomb(char * , wchar_t  ) ;
#line 138
extern size_t mbstowcs(wchar_t * __restrict   , char const   * __restrict   , size_t  ) ;
#line 139
extern size_t wcstombs(char * __restrict   , wchar_t const   * __restrict   , size_t  ) ;
#line 140
extern size_t __ctype_get_mb_cur_max(void) ;
#line 141
extern int posix_memalign(void ** , size_t  , size_t  ) ;
#line 142
extern int setenv(char const   * , char const   * , int  ) ;
#line 143
extern int unsetenv(char const   * ) ;
#line 144
extern int mkstemp(char * ) ;
#line 145
extern int mkostemp(char * , int  ) ;
#line 146
extern char *mkdtemp(char * ) ;
#line 147
extern int getsubopt(char ** , char * const  * , char ** ) ;
#line 148
extern int rand_r(unsigned int * ) ;
#line 149
extern char *realpath(char const   * __restrict   , char * __restrict   ) ;
#line 150
extern long random(void) ;
#line 151
extern void srandom(unsigned int  ) ;
#line 152
extern char *initstate(unsigned int  , char * , size_t  ) ;
#line 153
extern char *setstate(char * ) ;
#line 154
extern int putenv(char * ) ;
#line 155
extern int posix_openpt(int  ) ;
#line 156
extern int grantpt(int  ) ;
#line 157
extern int unlockpt(int  ) ;
#line 158
extern char *ptsname(int  ) ;
#line 159
extern char *l64a(long  ) ;
#line 160
extern long a64l(char const   * ) ;
#line 161
extern void setkey(char const   * ) ;
#line 162
extern double drand48(void) ;
#line 163
extern double erand48(unsigned short * ) ;
#line 164
extern long lrand48(void) ;
#line 165
extern long nrand48(unsigned short * ) ;
#line 166
extern long mrand48(void) ;
#line 167
extern long jrand48(unsigned short * ) ;
#line 168
extern void srand48(long  ) ;
#line 169
extern unsigned short *seed48(unsigned short * ) ;
#line 170
extern void lcong48(unsigned short * ) ;
#line 171
extern void *alloca(size_t  ) ;
#line 172
extern char *mktemp(char * ) ;
#line 173
extern int mkstemps(char * , int  ) ;
#line 174
extern int mkostemps(char * , int  , int  ) ;
#line 175
extern void *valloc(size_t  ) ;
#line 176
extern void *memalign(size_t  , size_t  ) ;
#line 177
extern int getloadavg(double * , int  ) ;
#line 178
extern int clearenv(void) ;
#line 179
extern void *reallocarray(void * , size_t  , size_t  ) ;
#line 180
extern void qsort_r(void * , size_t  , size_t  , int (*)(void const   * , void const   * ,
                                                         void * ) , void * ) ;
#line 191 "pid_controller_preprocessed.c"
float PID_Object_Step(PID *pid , Object *obj , float measurement , float setpoint ) 
{ 
  float err ;
  float deriv_filt ;
  float command ;
  float command_sat ;
  float F_sat ;
  float dv_dt ;

  {
#line 193
  err = setpoint - measurement;
#line 194
  pid->integral += (pid->Ki * err) * pid->T + (pid->Kaw * (pid->command_sat_prev - pid->command_prev)) * pid->T;
#line 195
  deriv_filt = ((err - pid->err_prev) + pid->T_C * pid->deriv_prev) / (pid->T + pid->T_C);
#line 196
  pid->err_prev = err;
#line 197
  pid->deriv_prev = deriv_filt;
#line 198
  command = (pid->Kp * err + pid->integral) + pid->Kd * deriv_filt;
#line 199
  pid->command_prev = command;
#line 201
  if (command > pid->max) {
#line 201
    command_sat = pid->max;
  } else
#line 202
  if (command < pid->min) {
#line 202
    command_sat = pid->min;
  } else {
#line 203
    command_sat = command;
  }
#line 204
  if (command_sat > pid->command_sat_prev + pid->max_rate * pid->T) {
#line 205
    command_sat = pid->command_sat_prev + pid->max_rate * pid->T;
  } else
#line 206
  if (command_sat < pid->command_sat_prev - pid->max_rate * pid->T) {
#line 207
    command_sat = pid->command_sat_prev - pid->max_rate * pid->T;
  }
#line 208
  pid->command_sat_prev = command_sat;
#line 210
  if (command_sat > obj->F_max) {
#line 210
    F_sat = obj->F_max;
  } else
#line 211
  if (command_sat < obj->F_min) {
#line 211
    F_sat = obj->F_min;
  } else {
#line 212
    F_sat = command_sat;
  }
#line 213
  dv_dt = (F_sat - obj->k * obj->v) / obj->m;
#line 214
  obj->v += dv_dt * obj->T;
#line 215
  simulate_seu_main(& obj->z);
#line 215
  obj->z += obj->v * obj->T;
#line 216
  return (obj->z);
}
}
#line 218 "pid_controller_preprocessed.c"
int main(void) 
{ 
  float t ;
  int i ;
  float command1 ;
  float command2 ;
  float stp1 ;
  float stp2 ;
  float z1 ;
  float z2 ;
  PID pid1 ;
  PID pid2 ;
  Object obj1 ;
  Object obj2 ;

  {
#line 220
  t = (float )0;
#line 221
  i = 0;
#line 222
  command1 = (float )0;
#line 222
  command2 = (float )0;
#line 223
  stp1 = (float )100;
#line 223
  stp2 = (float )50;
#line 224
  z1 = (float )0;
#line 224
  z2 = (float )0;
#line 225
  pid1.Kp = (float )1;
#line 225
  pid1.Ki = (float )0.1;
#line 225
  pid1.Kd = (float )5;
#line 225
  pid1.Kaw = (float )0.1;
#line 225
  pid1.T_C = (float )1;
#line 225
  pid1.T = (float )0.1;
#line 225
  pid1.max = (float )100;
#line 225
  pid1.min = (float )-100;
#line 225
  pid1.max_rate = (float )40;
#line 225
  pid1.integral = (float )0;
#line 225
  pid1.err_prev = (float )0;
#line 225
  pid1.deriv_prev = (float )0;
#line 225
  pid1.command_prev = (float )0;
#line 225
  pid1.command_sat_prev = (float )0;
#line 226
  pid2.Kp = (float )1.8;
#line 226
  pid2.Ki = (float )0.3;
#line 226
  pid2.Kd = (float )7;
#line 226
  pid2.Kaw = (float )0.3;
#line 226
  pid2.T_C = (float )1;
#line 226
  pid2.T = (float )0.1;
#line 226
  pid2.max = (float )100;
#line 226
  pid2.min = (float )-100;
#line 226
  pid2.max_rate = (float )40;
#line 226
  pid2.integral = (float )0;
#line 226
  pid2.err_prev = (float )0;
#line 226
  pid2.deriv_prev = (float )0;
#line 226
  pid2.command_prev = (float )0;
#line 226
  pid2.command_sat_prev = (float )0;
#line 227
  obj1.m = (float )10;
#line 227
  obj1.k = (float )0.5;
#line 227
  obj1.F_max = (float )100;
#line 227
  obj1.F_min = (float )-100;
#line 227
  obj1.T = (float )0.1;
#line 227
  obj1.v = (float )0;
#line 227
  simulate_seu_main(& obj1.z);
#line 227
  obj1.z = (float )0;
#line 228
  obj2.m = (float )10;
#line 228
  obj2.k = (float )0.5;
#line 228
  obj2.F_max = (float )100;
#line 228
  obj2.F_min = (float )-100;
#line 228
  obj2.T = (float )0.1;
#line 228
  obj2.v = (float )0;
#line 228
  obj2.z = (float )0;
#line 229
  while (i < 1000) {
#line 231
    if (t >= (float )60) {
#line 233
      stp1 = (float )200;
#line 234
      stp2 = (float )150;
    }
#line 236
    z1 = PID_Object_Step(& pid1, & obj1, z1, stp1);
#line 237
    z2 = PID_Object_Step(& pid2, & obj2, z2, stp2);
#line 238
    t = (float )((double )t + 0.1);
#line 239
    i ++;
  }
#line 241
  return (0);
}
}
